# Generated by Django 3.2.15 on 2022-08-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business_owner', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=255)),
                ('delivery', models.CharField(max_length=255)),
                ('commute', models.CharField(max_length=255)),
                ('challenges', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=255)),
                ('debtors', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('employees', models.CharField(max_length=255)),
                ('turnover', models.CharField(max_length=255)),
                ('sales', models.CharField(max_length=255)),
                ('cac', models.BooleanField(default=False)),
                ('council', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
