# Generated by Django 3.2.15 on 2022-08-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_name', models.CharField(max_length=50)),
                ('outter_name', models.CharField(max_length=50)),
                ('inner_name', models.CharField(max_length=50)),
                ('client_Passport_Img', models.ImageField(upload_to='images/')),
                ('client_Outter_Img', models.ImageField(upload_to='images/')),
                ('client_Inner_Img', models.ImageField(upload_to='images/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
