# Generated by Django 3.2.15 on 2022-09-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lga',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='stste',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='ward',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
