# Generated by Django 3.2.15 on 2022-08-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_hotel_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='kyc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.kyc'),
            preserve_default=False,
        ),
    ]
