# Generated by Django 3.2.15 on 2022-09-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_stste_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='wego_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
