# Generated by Django 3.2.15 on 2022-08-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shop_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
