# Generated by Django 3.2.15 on 2022-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shop_wego_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='lon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
