# Generated by Django 3.2.15 on 2022-08-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_drug_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='business_experience',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionaire',
            name='financial_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='have_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='loan_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='max_loan',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionaire',
            name='shop_experience',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
