# Generated by Django 3.2.15 on 2022-09-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220906_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
